version: "3"
services:
  
  backend:
    image: backend:v1.0
    environment:
      PROJECT_ID: "gke-webapp"

  frontend:
    image: frontend:v1.0
    environment:
      PROJECT_ID: "gke-webapp"
    ports:
      - "8080:8080"
    links:
      - backend:backend
    
