apiVersion: v1
kind: Service
metadata:
  labels:
    name: frontend-service
  name: frontend-service
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    name: frontend-node
  type: LoadBalancer
